from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parents[2]
RAW_DATA_DIR = PROJECT_ROOT / "Data"
DEMAND_DIR = RAW_DATA_DIR / "Demand"
OUTPUT_CAPABILITY_DIR = RAW_DATA_DIR / "Output_Capability"
VARIABLE_FORECAST_DIR = RAW_DATA_DIR / "VariableForecast"
STORAGE_DIR = RAW_DATA_DIR / "Storage"
GENERATOR_PARAMETERS_PATH = RAW_DATA_DIR / "GeneratorParamaters.csv"

PROCESSED_DIR = PROJECT_ROOT / "data" / "processed"
RESULTS_DIR = PROJECT_ROOT / "results"
FIGURES_DIR = PROJECT_ROOT / "figures"
REPORT_DIR = PROJECT_ROOT / "report"

MASTER_DATASET_PATH = PROCESSED_DIR / "master_hourly_dataset.csv"
RENEWABLE_GENERATOR_DATASET_PATH = PROCESSED_DIR / "renewable_generator_hourly_dataset.csv"
OBSERVED_STORAGE_BASELINE_PATH = PROCESSED_DIR / "observed_storage_hourly_baseline.csv"
DISPATCHABLE_GENERATOR_DATASET_PATH = PROCESSED_DIR / "dispatchable_generator_hourly_dataset.csv"
VARIABLE_FORECAST_SUMMARY_PATH = PROCESSED_DIR / "variable_forecast_publication_summary.json"

TRAIN_END = "2023-12-31 23:00:00"
VALID_START = "2024-01-01 00:00:00"
VALID_END = "2024-12-31 23:00:00"
TEST_START = "2025-01-01 00:00:00"
TEST_END = "2025-12-31 23:00:00"

ROUND_TRIP_EFFICIENCY = 0.90
STORAGE_DURATION_HOURS = 4.0
INITIAL_SOC_FRACTION = 0.5
LOAD_SHEDDING_PENALTY_PER_MWH = 10000.0
RENEWABLE_USAGE_REWARD_PER_MWH = 0.10
BATTERY_THROUGHPUT_PENALTY_PER_MWH = 0.05
